version: '3.7'

# Workflow
services:
  app:
    build:
      args:
        user: thiqat
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ecommerce-crud
    container_name: ecommerce-crud-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - ecommerce-crud

  db:
    image: mysql:5.7
    container_name: ecommerce-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/:/var/lib/mysql
    networks:
      - ecommerce-crud

  nginx:
    image: nginx:1.17-alpine
    container_name: ecommerce-nginx
    restart: unless-stopped
    ports:
      - 9050:80
    volumes:
      - ./:/var/www
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ecommerce-crud

networks:
  ecommerce-crud:
    driver: bridge
